apiVersion: v1
kind: Secret
metadata:
  name: openmaint-secret
  namespace: it
type: Opaque
stringData:
  db-name: "openmaint"
  db-user: "openmaint"
  db-password: "CHANGE_ME"
  postgres-password: "CHANGE_ME"
