deployment:
  replicas: 1

service:
  type: NodePort

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: INFO
