apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nifi-core
  namespace: it
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-nvme
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: nifi-core
